# Site
title:              Fundamentals
bio:                'Fundamentals of AI and Math.'
description:        "Zhizhong LI's personal site"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

collections:
  ai:
    output: true
    permalink: /:collection/:title
  art:
    output: true
    permalink: /:collection/:title
  life:
    output: true
    permalink: /:collection/:title
  math:
    output: true
    permalink: /:collection/:title
  music:
    output: true
    permalink: /:collection/:title
  sport:
    output: true
    permalink: /:collection/:title

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
# twitter:            default
# facebook:           default
# instagram:          default
github:             innerlee

# personal
location:           The Chinese University of Hong Kong
# phone:              1111111
email:              lizhizhong@outlook.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
